version: "2"
linters:
  default: all
  disable:
    # In many cases (e.g. options) it is normal usage not to specify all structure fields.
    - exhaustruct

    # TODO Temporary: Builder struct json field names do not comply with this rule,
    # but this struct will be refactored soon.
    - tagliatelle

    # Many go standard library API functions have typical parameter names shorter than 3 characters.
    # It is better to use the usual parameter names than to create one that conforms to the rule.
    - varnamelen

    # Except for general-purpose public APIs,
    # wrapping errors is more inconvenient and error prone than useful.
    - wrapcheck
  settings:
    depguard:
      rules:
        prevent_accidental_imports:
          allow:
            - $gostd
            - golang.org/x/mod
            - github.com/stretchr/testify/require
            - github.com/spf13/cobra
            - github.com/spf13/pflag
            - github.com/lmittmann/tint
            - github.com/mattn/go-isatty
            - github.com/mattn/go-colorable
            - github.com/fatih/color
            - github.com/Masterminds/semver/v3
            - github.com/go-git/go-git/v5
            - github.com/go-enry/go-license-detector/v4
            - github.com/szkiba/docsme
            - github.com/szkiba/efa
            - github.com/chainguard-dev/git-urls
            - github.com/charmbracelet/huh
            - github.com/grafana/k6foundry
            - go.k6.io/xk6
  exclusions:
    paths:
      # adopted from fixuid source: https://github.com/boxboat/fixuid
      - internal/fixids
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
