project_name: xk6
version: 2

env:
  - IMAGE=grafana/{{.ProjectName}}

before:
  hooks:
    - go mod tidy

builds:
  - id: xk6
    binary: xk6
    main: ./cmd/xk6
    goos: ["linux", "windows", "darwin"]
    goarch: ["amd64", "arm64"]
    flags: ["-trimpath"]
    env: ["CGO_ENABLED=0"]
    ldflags:
      - "-s -w"
      - "-X {{.ModulePath}}/internal/cmd.version={{.Version}}"
      - "-X {{.ModulePath}}/internal/cmd.appname={{.Binary}}"

  - id: xk6ea
    binary: xk6ea
    main: .
    goos: ["linux", "windows", "darwin"]
    goarch: ["amd64", "arm64"]
    flags: ["-trimpath"]
    env: ["CGO_ENABLED=0"]
    ldflags:
      - "-s -w"
      - "-X {{.ModulePath}}/internal/cmd.version={{.Version}}"
      - "-X {{.ModulePath}}/internal/cmd.appname={{.Binary}}"

  - id: fixids
    binary: fixids
    main: ./internal/fixids
    goos: ["linux"]
    goarch: ["amd64", "arm64"]
    flags: ["-trimpath"]
    env: ["CGO_ENABLED=0"]
    ldflags: ["-s -w"]

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

archives:
  - id: bundle
    builds: ["xk6", "xk6ea"]
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - READMEea.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next+{{.ShortCommit}}{{if .IsGitDirty}}.dirty{{else}}{{end}}"

dockers:
  - id: amd64
    ids: ["xk6", "fixids"]
    dockerfile: Dockerfile.goreleaser
    use: buildx
    extra_files: ["docker-entrypoint.sh"]
    image_templates:
      - 'docker.io/{{ .Env.IMAGE }}:{{ replace .Tag "v" "" }}-amd64'
      - "docker.io/{{ .Env.IMAGE }}:{{ .Major }}-amd64"
      - "docker.io/{{ .Env.IMAGE }}:{{ .Major }}.{{ .Minor }}-amd64"
      - "docker.io/{{ .Env.IMAGE }}:latest-amd64"

      - 'ghcr.io/{{ .Env.IMAGE }}:{{ replace .Tag "v" "" }}-amd64'
      - "ghcr.io/{{ .Env.IMAGE }}:{{ .Major }}-amd64"
      - "ghcr.io/{{ .Env.IMAGE }}:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/{{ .Env.IMAGE }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=AGPL-3.0-only"
  - id: arm64
    ids: ["xk6", "fixids"]
    dockerfile: Dockerfile.goreleaser
    use: buildx
    extra_files: ["docker-entrypoint.sh"]
    image_templates:
      - 'docker.io/{{ .Env.IMAGE }}:{{ replace .Tag "v" "" }}-arm64'
      - "docker.io/{{ .Env.IMAGE }}:{{ .Major }}-arm64"
      - "docker.io/{{ .Env.IMAGE }}:{{ .Major }}.{{ .Minor }}-arm64"
      - "docker.io/{{ .Env.IMAGE }}:latest-arm64"

      - 'ghcr.io/{{ .Env.IMAGE }}:{{ replace .Tag "v" "" }}-arm64'
      - "ghcr.io/{{ .Env.IMAGE }}:{{ .Major }}-arm64"
      - "ghcr.io/{{ .Env.IMAGE }}:{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/{{ .Env.IMAGE }}:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=AGPL-3.0-only"

docker_manifests:
  - id: tag
    name_template: 'docker.io/{{ .Env.IMAGE }}:{{ replace .Tag "v" "" }}'
    image_templates:
      - 'docker.io/{{ .Env.IMAGE }}:{{ replace .Tag "v" "" }}-amd64'
      - 'docker.io/{{ .Env.IMAGE }}:{{ replace .Tag "v" "" }}-arm64'
  - id: major
    name_template: "docker.io/{{ .Env.IMAGE }}:{{ .Major }}"
    image_templates:
      - "docker.io/{{ .Env.IMAGE }}:{{ .Major }}-amd64"
      - "docker.io/{{ .Env.IMAGE }}:{{ .Major }}-arm64"
  - id: major-minor
    name_template: "docker.io/{{ .Env.IMAGE }}:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "docker.io/{{ .Env.IMAGE }}:{{ .Major }}.{{ .Minor }}-amd64"
      - "docker.io/{{ .Env.IMAGE }}:{{ .Major }}.{{ .Minor }}-arm64"
  - id: latest
    name_template: "docker.io/{{ .Env.IMAGE }}:latest"
    image_templates:
      - "docker.io/{{ .Env.IMAGE }}:latest-amd64"
      - "docker.io/{{ .Env.IMAGE }}:latest-arm64"

  - id: tag-ghcr
    name_template: 'ghcr.io/{{ .Env.IMAGE }}:{{ replace .Tag "v" "" }}'
    image_templates:
      - 'ghcr.io/{{ .Env.IMAGE }}:{{ replace .Tag "v" "" }}-amd64'
      - 'ghcr.io/{{ .Env.IMAGE }}:{{ replace .Tag "v" "" }}-arm64'
  - id: major-ghcr
    name_template: "ghcr.io/{{ .Env.IMAGE }}:{{ .Major }}"
    image_templates:
      - "ghcr.io/{{ .Env.IMAGE }}:{{ .Major }}-amd64"
      - "ghcr.io/{{ .Env.IMAGE }}:{{ .Major }}-arm64"
  - id: major-minor-ghcr
    name_template: "ghcr.io/{{ .Env.IMAGE }}:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/{{ .Env.IMAGE }}:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/{{ .Env.IMAGE }}:{{ .Major }}.{{ .Minor }}-arm64"
  - id: latest-ghcr
    name_template: "ghcr.io/{{ .Env.IMAGE }}:latest"
    image_templates:
      - "ghcr.io/{{ .Env.IMAGE }}:latest-amd64"
      - "ghcr.io/{{ .Env.IMAGE }}:latest-arm64"
