name: Extension Validate

on:
  workflow_call:
    secrets:
      # #region secrets
      codecov-token:
        description: Token to be used to upload test coverage data to Codecov.
        required: false
      # #endregion secrets
    inputs:
      # #region inputs
      go-version:
        description: The go version to use for the build.
        required: true
        type: string
      go-versions:
        description: The go versions to use for running the tests. JSON string array (e.g. ["1.24.x", "1.23.x"])
        required: true
        type: string
      platforms:
        description: Platforms to be used to run the tests. JSON string array (e.g. ["ubuntu-latest","macos-latest"])
        required: true
        type: string
      golangci-lint-version:
        description: The golangci-lint version to use for static analysis.
        required: true
        type: string
      passing-grade:
        description: Passing compliance grade
        type: string
        required: false
        default: C
      public:
        description: Static content directory for GitHub Pages
        type: string
        required: false
        default: public
      k6-versions:
        description: The k6 versions to be used for integration tests. JSON string array (e.g. ["v0.57.0","v0.56.0"])
        required: false
        default: '["latest"]'
        type: string
      xk6-version:
        description: The xk6 version to be used.
        required: true
        type: string
      bats:
        description: The bats scripts to use for integration testing. Space-separated file names or patterns.
        type: string
        required: false
      # #endregion inputs

jobs:
  config:
    name: Config
    runs-on: ubuntu-latest
    outputs:
      devcontainer: ${{steps.configure.outputs.devcontainer}}
      codecov: ${{steps.configure.outputs.codecov}}
      api-doc: ${{steps.configure.outputs.api-doc}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Configure
        id: configure
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "${{secrets.codecov-token}}" ] ; then
            echo "codecov=true" >> $GITHUB_OUTPUT
          fi
          if [ -f ".devcontainer/devcontainer.json" ]; then
            echo "devcontainer=true" >> $GITHUB_OUTPUT
          fi
          if [ -f 'index.d.ts' ]; then
            if [ -f 'tsconfig.json' ] || [ -f 'typedoc.json' ]; then
              if gh api --silent /repos/${{github.repository}}/pages >/dev/null 2>&1; then
                echo "api-doc=true" >> $GITHUB_OUTPUT
              else
                echo "::warning::GitHub Pages is not enabled for this repository. Please enable it to generate API documentation."
              fi
            fi
          fi
      - name: Summary
        shell: bash
        env:
          GO_VERSION: ${{inputs.go-version}}
          GO_VERSIONS: ${{ join(fromJSON(inputs.go-versions),' ') }}
          GOLANGCI_LINT_VERSION: ${{inputs.golangci-lint-version}}
          K6_VERSIONS: ${{ join(fromJSON(inputs.k6-versions),' ') }}
          PLATFORMS: ${{ join(fromJSON(inputs.platforms),' ') }}
          API_DOC: ${{ steps.configure.outputs.api-doc }}
          CODECOV: ${{ steps.configure.outputs.codecov }}
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<END

          ### Configuration

          Description           | Value
          ----------------------|--------------------------------
          go version for build  | ${GO_VERSION}
          go versions for test  | ${GO_VERSIONS}
          platforms for test    | ${PLATFORMS}
          golangci-lint version | ${GOLANGCI_LINT_VERSION}
          k6 versions for test  | ${K6_VERSIONS}

          END

          if [ -n "${API_DOC}" ]; then
            echo "API documentation will be generated." >> $GITHUB_STEP_SUMMARY
          fi

          if [ -n "${CODECOV}" ]; then
            echo "Coverage data will be uploaded to Codecov." >> $GITHUB_STEP_SUMMARY
          fi

  security:
    name: Security
    runs-on: ubuntu-latest
    needs: ["config"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Gosec Security Scanner
        uses: securego/gosec@d2d3ae66bd8d340b78b5142b6fe610691783c2fe # v2.22.5
        with:
          args: ./...

      - name: Run Vulnerability Checker
        id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-input: ${{inputs.go-version}}
          go-package: ./...

  compliance:
    name: Compliance
    needs: ["security"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go ${{inputs.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{inputs.go-version}}

      - name: Setup xk6 ${{ inputs.xk6-version }}
        uses: grafana/setup-xk6@v1.0.0
        with:
          xk6-version: ${{ inputs.xk6-version }}

      - name: Run xk6 lint
        shell: bash
        env:
          PASSING_GRADE: ${{ inputs.passing-grade }}
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<END

          ### Compliance

          ~~~
          END

          set -e
          xk6 lint --passing ${PASSING_GRADE} --passed security,vulnerability | tee -a $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: ["security"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go ${{ inputs.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Check module dependencies
        shell: bash
        run: |
          go version
          test -z "$(go mod tidy && git status go.* --porcelain)"
          go mod verify

      - name: Run minimal golangci-lint ${{ inputs.golangci-lint-version }}
        if: ${{ hashFiles('.golangci.yml','.golangci.yaml','.golangci.toml','.golangci.json') == ''}}
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: "${{ inputs.golangci-lint-version }}"
          args: --timeout=30m --no-config

      - name: Run configured golangci-lint ${{ inputs.golangci-lint-version }}
        if: ${{ hashFiles('.golangci.yml','.golangci.yaml','.golangci.toml','.golangci.json') != ''}}
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: "${{ inputs.golangci-lint-version }}"
          only-new-issues: true
          args: --timeout=30m

  smoke:
    name: Smoke
    runs-on: ubuntu-latest
    needs: ["security"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go ${{ inputs.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Run tests
        run: |
          go test -short -timeout 2m ./...

  test:
    name: Test
    needs:
      - lint
      - smoke
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJSON(inputs.go-versions) }}
        platform: ${{ fromJSON(inputs.platforms) }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: |
          go test -race -timeout 2m ./...

  build:
    name: Build
    needs:
      - lint
      - smoke
    strategy:
      fail-fast: false
      matrix:
        k6-version: ${{ fromJSON(inputs.k6-versions) }}
        go-version: ${{ fromJSON(inputs.go-versions) }}
        platform: ${{ fromJSON(inputs.platforms) }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Bats
        if: ${{ inputs.bats != '' && runner.os == 'Linux' }}
        uses: bats-core/bats-action@42fcc8700f773c075a16a90eb11674c0318ad507 # 3.0.1
        with:
          bats-version: "1.11.1"

      - name: Setup xk6 ${{ inputs.xk6-version }}
        uses: grafana/setup-xk6@v1.0.0
        with:
          xk6-version: ${{ inputs.xk6-version }}

      - name: Build k6
        shell: bash
        env:
          K6_VERSION: ${{ matrix.k6-version }}
        run: |
          MODULE=$(go list -f '{{.Module.Path}}')
          xk6 build -v --with ${MODULE}="."

      - name: Run k6 version
        shell: bash
        run: ./k6 version

      - name: Integration Test
        if: ${{ inputs.bats != '' && runner.os == 'Linux' }}
        env:
          K6_VERSIONS: ${{ join(fromJSON(inputs.k6-versions),' ') }}
          K6: "${{github.workspace}}/k6"
          BATS: ${{ inputs.bats }}
        shell: bash
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<END

          ### Integration Test

          END

          set -e
          bats ${BATS} | tee -a $GITHUB_STEP_SUMMARY

  report:
    name: Report
    needs:
      - config
      - test
      - build
    if: ${{ (github.ref_name == 'main' || github.ref_name == 'master') && (needs.config.outputs.codecov == 'true') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go ${{inputs.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: "${{inputs.go-version}}"

      - name: Test
        run: go test -count 1 -coverprofile=coverage.txt ./...

      - name: Upload Coverage
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{secrets.codecov-token}}
          slug: ${{github.repository}}

      - name: Generate Go Report Card
        uses: creekorful/goreportcard-action@1f35ced8cdac2cba28c9a2f2288a16aacfd507f9 # v1.0

  pages:
    name: Pages
    needs: ["config"]
    if: ${{ needs.config.outputs.api-doc }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: Prepare htdocs
        run: mkdir -p ${{runner.temp}}/htdocs

      - name: Generate API doc
        run: |
          if [ -f index.d.ts ]; then
            bun x typedoc --out ${{runner.temp}}/htdocs
            cp index.d.ts ${{runner.temp}}/htdocs/
          fi

      - name: Copy static content
        shell: bash
        env:
          PUBLIC: ${{ inputs.public }}
        run: |
          if test -d "${PUBLIC}"; then
            cp -a ${PUBLIC}/. ${{runner.temp}}/htdocs/
          fi

      - name: Setup Pages
        if: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{runner.temp}}/htdocs

      - name: Deploy to GitHub Pages
        if: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}
        uses: actions/deploy-pages@v4

  devcontainer:
    name: DevContainer
    needs: ["config"]
    if: ${{ needs.config.outputs.devcontainer }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      GO_VERSION: ""
      GOLANGCI_LINT_VERSION: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Config
        run: |
          cat .devcontainer/devcontainer.json | jq -r '
            {
              GO_VERSION: .features["ghcr.io/devcontainers/features/go:1"]["version"],
              GOLANGCI_LINT_VERSION: .features["ghcr.io/devcontainers/features/go:1"]["golangciLintVersion"]
            } | to_entries | map("\(.key)=\(.value|tostring)")|.[]' >> "$GITHUB_ENV"

      - name: Check go version ${{inputs.go-version}}
        shell: bash
        env:
          INPUT_GO_VERSION: ${{inputs.go-version}}
        run: |
          if [ ! "${{env.GO_VERSION}}" == "$(echo ${INPUT_GO_VERSION}|sed -e 's/\.x//g')" ]; then
            echo "::error::Mismatched go versions in devcontainers.json and workflow input"
            exit 1
          fi

      - name: Check golangci-lint version ${{inputs.golangci-lint-version}}
        shell: bash
        env:
          INPUT_GOLANGCI_LINT_VERSION: ${{inputs.golangci-lint-version}}
        run: |
          if [ ! "${{env.GOLANGCI_LINT_VERSION}}" == "$(echo ${INPUT_GOLANGCI_LINT_VERSION}|sed -e 's/v//g')" ]; then
            echo "::error::Mismatched golangci-lint versions in devcontainers.json and workflow input"
            exit 1
          fi
