name: Extension Release

on:
  workflow_call:
    inputs:
      # #region inputs
      k6-version:
        description: The k6 versions to be used.
        type: string
        required: true
      xk6-version:
        description: The xk6 versions to be used.
        type: string
        required: true
      go-version:
        description: The go version to use for the build.
        type: string
        required: true
      os:
        description: Target GOOS values. JSON string array (e.g. ["linux","windows","darwin"])
        type: string
        required: true
      arch:
        description: Target GOARCH values. JSON string array (e.g. ["amd64","arm64"])
        type: string
        required: true
      with:
        description: List of additional extension modules to be included.
        type: string
        required: false
      cgo:
        description: Enable CGO
        type: boolean
      private:
        description: The repository is private
        type: boolean
      bats:
        description: The bats scripts to use for integration testing. Space-separated file names or patterns.
        type: string
        required: false
      # #endregion inputs

jobs:
  config:
    name: Config
    runs-on: ubuntu-latest
    outputs:
      module-path: ${{steps.module.outputs.path}}
      repository-name: ${{steps.repository.outputs.name}}
      version: ${{steps.version.outputs.version}}
      with: ${{steps.with.outputs.with}}
      cgo: ${{steps.cgo.outputs.cgo}}
      goprivate: ${{steps.goprivate.outputs.goprivate}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Detect go module path
        id: module
        shell: bash
        run: |
          echo "path=$(go list -f '{{.Module.Path}}')" >> $GITHUB_OUTPUT
      - name: Parse repository name
        id: repository
        shell: bash
        run: |
          echo "name=$(echo ${{github.repository}}|cut -d/ -f2)" >> $GITHUB_OUTPUT
      - name: Version from input or tag
        id: version
        shell: bash
        env:
          REF_TYPE: ${{github.ref_type}}
          REF_NAME: ${{github.ref_name}}
        run: |
          if [ "${REF_TYPE}" == "tag" ]; then
            echo "version=${REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "The run was not triggered by a git tag push." >&2
            exit 1
          fi
      - name: Prepare extra --with arguments
        id: with
        shell: bash
        env:
          WITH: ${{inputs.with}}
        run: |
          if [ -z "${WITH}" ]; then
            exit 0
          fi
          value=$(for part in $(echo "${WITH}"); do echo -n " --with $part" ; done)
          echo "with=$value" >> $GITHUB_OUTPUT
      - name: Prepare CGO environment valiable
        id: cgo
        shell: bash
        env:
          CGO: ${{inputs.cgo}}
        run: |
          cgo="0"
          if [ "${CGO}" == "true" ]; then
            cgo="1"
          fi
          echo "cgo=${cgo}" >> $GITHUB_OUTPUT
      - name: Prepare GOPRIVATE environment valiable
        id: goprivate
        shell: bash
        env:
          PRIVATE: ${{inputs.private}}
        run: |
          goprivate=""
          if [ "${PRIVATE}" == "true" ]; then
            goprivate="$(go list -f '{{.Module.Path}}')"
          fi
          echo "goprivate=${goprivate}" >> $GITHUB_OUTPUT
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: |
            LICENSE*
            README.md
      - name: Summary
        env:
          GO_VERSION: ${{ inputs.go-version }}
          K6_VERSION: ${{ inputs.k6-version }}
          XK6_VERSION: ${{ inputs.xk6-version }}
          WITH: ${{ inputs.with }}
          OS: ${{ join(fromJSON(inputs.os),', ') }}
          ARCH: ${{ join(fromJSON(inputs.arch),', ') }}
          REF_NAME: ${{ github.ref_name }}
        shell: bash
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<END

          ## ${REF_NAME}

          ### Configuration

          Description          | Value
          ------------|-----------------------------
          go version  | ${GO_VERSION}
          k6 version  | ${K6_VERSION}
          xk6 version | ${XK6_VERSION}
          os          | ${OS}
          arch        | ${ARCH}
          with        | ${WITH}

          END

  security:
    name: Security
    runs-on: ubuntu-latest
    needs: ["config"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Gosec Security Scanner
        uses: securego/gosec@d2d3ae66bd8d340b78b5142b6fe610691783c2fe # v2.22.5
        with:
          args: ./...

      - name: Run Vulnerability Checker
        id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-input: ${{inputs.go-version}}
          go-package: ./...

  build:
    name: Build
    needs: ["config", "security"]
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.os) }}
        arch: ${{ fromJSON(inputs.arch) }}
    env:
      DIST_DIR: ${{needs.config.outputs.repository-name}}_${{needs.config.outputs.version}}_${{matrix.os}}_${{matrix.arch}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup Go ${{ inputs.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Setup Bats
        if: ${{ inputs.bats != '' && runner.os == 'Linux' }}
        uses: bats-core/bats-action@42fcc8700f773c075a16a90eb11674c0318ad507 # 3.0.1
        with:
          bats-version: "1.11.1"

      - name: Setup xk6 ${{ inputs.xk6-version }}
        uses: grafana/setup-xk6@v1.0.0
        with:
          xk6-version: ${{ inputs.xk6-version }}

      - name: Build k6
        shell: bash
        env:
          GOOS: ${{matrix.os}}
          GOARCH: ${{matrix.arch}}
          CGO: ${{needs.config.outputs.cgo}}
          GOPRIVATE: ${{needs.config.outputs.goprivate}}
          GH_TOKEN: ${{github.token}}
          K6_VERSION: ${{ inputs.k6-version }}
          MODULE_PATH: ${{needs.config.outputs.module-path}}
          VERSION: ${{needs.config.outputs.version}}
          WITH: ${{needs.config.outputs.with}}
        run: |
          mkdir -p $DIST_DIR
          cd $DIST_DIR
          git config --global --add 'credential.https://github.com.helper' '!gh auth git-credential'
          xk6 build --with ${MODULE_PATH}@${VERSION} ${WITH}

      - name: Integration Test
        if: ${{ env.bats != '' && runner.os == 'Linux' }}
        env:
          K6_VERSION: ${{ inputs.k6-version }}
          K6: ${{env.DIST_DIR}}/k6
          BATS: ${{ inputs.bats }}
        shell: bash
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<END

          ### Integration Test

          END

          set -e
          bats $BATS | tee -a $GITHUB_STEP_SUMMARY

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{env.DIST_DIR}}
          name: files

      - name: Create Archive
        shell: bash
        env:
          OS: ${{matrix.os}}
        run: |
          if [ "${OS}" == "windows" ]; then
            zip -r ${DIST_DIR}.zip $DIST_DIR
          else
            tar czf ${DIST_DIR}.tar.gz $DIST_DIR
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{env.DIST_DIR}}.*
          name: archive-${{matrix.os}}_${{matrix.arch}}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
      - config
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
          pattern: archive-*

      - name: Create Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: dist/*
          tag_name: ${{needs.config.outputs.version}}
