name: Tooling Release

on:
  workflow_call:
    inputs:
      # #region inputs
      go-version:
        description: The go version to use for the build.
        required: true
        type: string
      goreleaser-version:
        description: The version of GoReleaser to use for builds and releases.
        required: true
        type: string
      k6-versions:
        description: The k6 versions to be used for integration tests. JSON string array (e.g. ["v0.57.0","v0.56.0"])
        required: false
        default: '["latest"]'
        type: string
      bats:
        description: The bats scripts to use for integration testing. Space-separated file names or patterns.
        type: string
        required: false
      # #endregion inputs

jobs:
  config:
    name: Config
    runs-on: ubuntu-latest
    outputs:
      docker: ${{steps.configure.outputs.docker}}
      docker-io: ${{steps.configure.outputs.docker-io}}
      ghcr-io: ${{steps.configure.outputs.ghcr-io}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Configure
        id: configure
        run: |
          if yq -r '.dockers[].image_templates[]' .goreleaser.y*ml | grep -q ghcr.io ; then
            echo "docker=true" >> $GITHUB_OUTPUT
            echo "ghcr-io=true" >> $GITHUB_OUTPUT
          fi
          if yq -r '.dockers[].image_templates[]' .goreleaser.y*ml | grep -q docker.io ; then
            echo "docker=true" >> $GITHUB_OUTPUT
            echo "docker-io=true" >> $GITHUB_OUTPUT
          fi
      - name: Summary
        env:
          REF_NAME: ${{ github.ref_name }}
          GO_VERSION: ${{ inputs.go-version }}
          GORELEASER_VERSION: ${{ inputs.goreleaser-version }}
          K6_VERSIONS: ${{ join(fromJSON(inputs.k6-versions),' ') }}
          GHCR_IO: ${{ steps.configure.outputs.ghcr-io }}
          DOCKER_IO: ${{ steps.configure.outputs.docker-io }}
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<END

          ## ${REF_NAME}

          ### Configuration

          Description          | Value
          ---------------------|-----------------------------
          go version for build | ${GO_VERSION}
          GoReleaser version   | ${GORELEASER_VERSION}
          k6 versions for test | ${K6_VERSIONS}

          END

          if [ -n "${GHCR_IO}" ]; then
            echo "Push Docker image to ghcr.io" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -n "${DOCKER_IO}" ]; then
            echo "Push Docker image to docker.io" >> $GITHUB_STEP_SUMMARY
          fi

  security:
    name: Security
    runs-on: ubuntu-latest
    needs: ["config"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Gosec Security Scanner
        uses: securego/gosec@d2d3ae66bd8d340b78b5142b6fe610691783c2fe # v2.22.5
        with:
          args: ./...

      - name: Run Vulnerability Checker
        id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-input: ${{inputs.go-version}}
          go-package: ./...

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ["config", "security"]
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go ${{ inputs.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: "${{ inputs.go-version }}"
          cache: false

      - name: Set up QEMU
        if: ${{needs.config.outputs.docker == 'true'}}
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          platforms: "amd64,arm64"

      - name: Setup Bats
        if: ${{ inputs.bats != '' && runner.os == 'Linux' }}
        uses: bats-core/bats-action@42fcc8700f773c075a16a90eb11674c0318ad507 # 3.0.1
        with:
          bats-version: "1.11.1"

      - name: GoReleaser snapshot
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          version: "${{ inputs.goreleaser-version }}"
          args: release --clean --snapshot

      - name: Integration Test
        if: ${{ env.bats != '' }}
        env:
          K6_VERSIONS: ${{ join(fromJSON(inputs.k6-versions),' ') }}
          BATS: ${{ inputs.bats }}
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<END

          ### Integration Test

          END

          set -e
          bats $BATS | tee -a $GITHUB_STEP_SUMMARY

      - name: Login to Docker Hub
        if: ${{ needs.config.outputs.docker-io == 'true' }}
        uses: grafana/shared-workflows/actions/dockerhub-login@13fb504e3bfe323c1188bf244970d94b2d336e86 # dockerhub-login-v1.0.1

      - name: Login to GitHub Packages
        if: ${{ needs.config.outputs.ghcr-io == 'true' }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: GoReleaser release
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          version: "${{ inputs.goreleaser-version }}"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
